spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboarddb?useSSL=false&serverTimezone=UTC
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
